Financas/Models/BuscaMovimentacoesModel.cs
using Financas.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Financas.Models
{
    public class BuscaMovimentacoesModel
    {
        public decimal? ValorMinimo { get; set; }
        public decimal? ValorMaximo { get; set; }
        public DateTime? DataMinima { get; set; }
        public DateTime? DataMaxima { get; set; }
        public Tipo? Tipo { get; set; }
        public int? UsuarioId { get; set; }
        public IList<Movimentacao> Movimentacoes { get; set; }
        public IList<Usuario> Usuarios { get; set; }


    }
}

Financas/Models/MovimentacoesPorUsuarioModel.cs
using Financas.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Financas.Models
{
    public class MovimentacoesPorUsuarioModel
    {
        public int? UsuarioId { get; set; }
        public IList<Movimentacao> Movimentacoes { get; set; }
        public IList<Usuario> usuarios { get; set; }
    }
}

Financas/Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Financas.Models
{
    public class UsuarioModel
    {
        [Required]
        public string Nome { get; set; }
        [Required, EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Senha { get; set; }
        [Compare("Senha")]
        public string ConfirmacaoSenha { get; set; }
    }
}

Financas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Financas.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Financas/Controllers/LoginController.cs
using System;
using System.Web.Mvc;
using WebMatrix.WebData;

namespace Financas.Controllers
{
    public class LoginController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autentica(String login, String senha)
        {
            if(WebSecurity.Login(login, senha))
            {
                return RedirectToAction("Index","Home");
            }
            else
            {
                ModelState.AddModelError("login.Invalido", "Login ou senha Incorretos");
                return View("Index");
            }
        }

        public ActionResult Logout()
        {
            WebSecurity.Logout();
            return RedirectToAction("Index");
        }
    }
}

Financas/Controllers/MovimentacaoController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Financas.DAO;
using Financas.Entidades;
using Financas.Models;

namespace Financas.Controllers
{
    [Authorize]
    public class MovimentacaoController : Controller
    {
        private MovimentacaoDAO movimentacaoDAO;
        private UsuarioDAO usuarioDAO;
        public MovimentacaoController(MovimentacaoDAO movimentacaoDAO, UsuarioDAO usuarioDAO)
        {
            this.movimentacaoDAO = movimentacaoDAO;
            this.usuarioDAO = usuarioDAO;
        }
        
        
        // GET: Movimentacao
        public ActionResult Form()
        {
            ViewBag.Usuarios = usuarioDAO.Lista();
            return View();
        }

        public ActionResult Adiciona(Movimentacao movimentacao)
        {
            if (ModelState.IsValid)
            {
                movimentacaoDAO.Adiciona(movimentacao);
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Usuarios = usuarioDAO.Lista();
                return View("Form", movimentacao);
            }
        }

        public ActionResult Index()
        {
            IList<Movimentacao> movimentacoes = movimentacaoDAO.Lista();
            return View(movimentacoes);
        }

        public ActionResult MovimentacoesPorUsuario(MovimentacoesPorUsuarioModel model)
        {
            model.usuarios = usuarioDAO.Lista();
            model.Movimentacoes = movimentacaoDAO.BuscaPorUsuario(model.UsuarioId);
            return View(model);
        }

        public ActionResult Busca(BuscaMovimentacoesModel model)
        {
            model.Usuarios = usuarioDAO.Lista();
            model.Movimentacoes = movimentacaoDAO.Busca(model.ValorMinimo, model.ValorMaximo,
                model.DataMinima,model.DataMaxima,model.Tipo,model.UsuarioId);

            return View(model);
        }
    }
}

Financas/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Financas.DAO;
using Financas.Entidades;
using Financas.Models;
using WebMatrix.WebData;
using System.Web.Security;

namespace Financas.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        private UsuarioDAO usuarioDAO;
        public UsuarioController(UsuarioDAO usuarioDAO)
        {
            this.usuarioDAO = usuarioDAO;
        }
        // GET: Usuario
        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(UsuarioModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    WebSecurity.CreateUserAndAccount(model.Nome, model.Senha, 
                        new {Email = model.Email });
                    return RedirectToAction("Index");
                }
                catch(MembershipCreateUserException e)
                {
                    ModelState.AddModelError("Usuario invalido", e.Message);
                    return View("Form", model);
                }
                
            }
            else
            {
                return View("Form", model);
            }
        }

        public ActionResult Index()
        {
            IList<Usuario> usuarios = usuarioDAO.Lista();
            return View(usuarios);
        }
    }
}

Financas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
Bem Vindo ao Controle Financeiro

Financas/Views/Login/Index.cshtml
@{
    ViewBag.Title = "Login";
}
<form action="@Url.Action("Autentica")" method="post">
    @Html.ValidationMessage("login.Invalido","", new { @class = "text-danger" })
    <br />
    <label for="login">Login</label>
    <input id="login" name="login" type="text" class="form-control"/>
    <br />
    <label for="senha">Senha</label>
    <input id="senha" name="senha" type="password" class="form-control"/>
    <br />
    <input type="submit" value="Autenticar" class="btn btn-success"/>
    
</form>

Financas/Views/Movimentacao/Busca.cshtml
@model Financas.Models.BuscaMovimentacoesModel
    @{
    ViewBag.Title = "Pesquisar";
}

@using (Html.BeginForm("Busca", "Movimentacao", FormMethod.Get))
{
    <div class="row">
        <fieldset>
            <legend>Data Movimentação</legend>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.DataMinima, "Minima")
                @Html.TextBoxFor(b => b.DataMinima, new {@class="form-control" } )
            </div>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.DataMaxima, "Maxima")
                @Html.TextBoxFor(b => b.DataMaxima, new {@class="form-control" } )
            </div>
        </fieldset>

        <fieldset>
            <legend>Valor Movimentação</legend>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.ValorMinimo, "Minimo")
                @Html.TextBoxFor(b => b.ValorMinimo, new {@class="form-control" } )
            </div>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.ValorMaximo, "Maximo")
                @Html.TextBoxFor(b => b.ValorMaximo, new {@class="form-control" } )
            </div>
        </fieldset>

         <fieldset>
            <legend>Usuario e Tipo</legend>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.Tipo, "Tipo")
                @Html.EnumDropDownListFor(b => b.Tipo, new {@class="form-control" } )
            </div>
            <div class="col-sm-6">
                @Html.LabelFor(b => b.UsuarioId, "Usuario")
                @Html.DropDownListFor(b => b.UsuarioId,
                            new SelectList(Model.Usuarios,"Id", "Nome"),
                            "Escola Um Usuairo")
            </div>
        </fieldset>
        <br />
        <input type="submit" value="Buscar" class="btn btn-info"/>
    </div>
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Data</th>
            <th>Valor</th>
            <th>Tipo</th>
            <th>Usuario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var t in Model.Movimentacoes)
        {
            <tr>
                <th>@t.Id</th>
                <th>@t.Data</th>
                <th>@t.Valor</th>
                <th>@t.Tipo</th>
                <th>@t.Usuario.Nome</th>
            </tr>

        }
    </tbody>
</table>

Financas/Views/Movimentacao/Form.cshtml
@model Financas.Entidades.Movimentacao
@{
    ViewBag.Title = "Nova Movimentação";
}    
@using (Html.BeginForm("Adiciona", "Movimentacao", FormMethod.Post))
{
    @Html.LabelFor(m => m.Valor, "Valor:")
    @Html.TextBoxFor(m => m.Valor, new {@class="form-control"})
    @Html.ValidationMessageFor(m => m.Valor)
    <br/>

    @Html.LabelFor(m => m.UsuarioId, "Usuario:")
    @Html.DropDownListFor(m => m.UsuarioId,
        new SelectList(ViewBag.Usuarios, "Id", "Nome"),
        new {@class="form-control"})

    @Html.ValidationMessageFor(m => m.UsuarioId)
    <br />
    @Html.LabelFor(m=> m.Tipo, "Tipo:")
    @Html.EnumDropDownListFor(m => m.Tipo, new {@class= "form-control"})
    @Html.ValidationMessageFor(m => m.Tipo)
    <br />
    @Html.LabelFor(m=> m.Data,  "Data:")
    @Html.TextBoxFor(m=> m.Data, new {@class="form-control"})
    @Html.ValidationMessageFor(m=> m.Data)
    <br/>
    <input type="submit" value="Salvar" class="btn btn-primary"/>
}

Financas/Views/Movimentacao/Index.cshtml
@model IList<Financas.Entidades.Movimentacao>
    @{
    ViewBag.Title = "Movimentações";
}

@Html.ActionLink("Nova Movimentação", "Form", "Movimentacao")

<table class="table table-hover">
    <thead>
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Valor</th>
        <th>Tipo</th>
    </tr>
    </thead>

    <tbody>
    @foreach(var m in Model)
    {
        <tr>
            <td>@m.Id</td>
            <td>@m.Usuario.Nome</td>
            <td>@m.Valor</td>
            <td>@m.Tipo</td>
        </tr>
    }
    </tbody>
</table>

Financas/Views/Movimentacao/MovimentacoesPorUsuario.cshtml
@model Financas.Models.MovimentacoesPorUsuarioModel
    @{
    ViewBag.Title = "Pesquisa Por Usuario";
}

@using (Html.BeginForm("MovimentacoesPorUsuario", "Movimentacao", FormMethod.Get))
{
    @Html.LabelFor(m => m.UsuarioId, "Usuario")
    @Html.DropDownListFor(m => m.UsuarioId,
            new SelectList(Model.usuarios, "Id", "Nome"),
            "Escolha Um Usuario")

    <br />
    <input type="submit" value="Buscar" class="btn btn-primary"/>
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>Usuario</th>
            <th>Tipo</th>
            <th>Valor</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var m in Model.Movimentacoes)
        {
            <tr>
                <td>@m.Usuario.Nome</td>
                <td>@m.Tipo</td>
                <td>@m.Valor</td>
            </tr>
        }
    </tbody>
</table>

Financas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Finanças</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
   @Html.Partial("_MenuSuperior")
<div class="container">
    <main class="col-sm-8">
        @RenderBody()
    </main>
    @if (User.Identity.IsAuthenticated)
     {
     <aside class="col-sm-4">
        <h3>Acesso Rapido</h3>
        <ul>
            <li>@Html.ActionLink("Movimentacoes por Usuario", "MovimentacoesPorUsuario", "Movimentacao")</li>
            <li>@Html.ActionLink("Busca de Movimentacoes", "Busca", "Movimentacao")</li>
        </ul>
    </aside>
      }
</div>
</body>
</html>

Financas/Views/Shared/_MenuSuperior.cshtml
<nav>
    <div class="container-fluid">
        <ul class="nav nav-tabs">
         @if (User.Identity.IsAuthenticated)
         {
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Usuario", "Index", "Usuario")</li>
            <li>@Html.ActionLink("Movimentacoes", "Index", "Movimentacao")</li>
         }


            @if (User.Identity.IsAuthenticated)
            {
                <li>@Html.ActionLink("Logoff", "Logout", "Login")</li>
            }
            else
            {
                <li>@Html.ActionLink("Login", "Index", "Login")</li>
                
            }
            
            
        </ul> 
    </div>
</nav>

Financas/Views/Usuario/Form.cshtml
@model Financas.Models.UsuarioModel
    @{
    ViewBag.Title = "Nova Usuario";
}
    
@using (Html.BeginForm("Adiciona","Usuario", FormMethod.Post, new {@class= ""}))
{
  @Html.ValidationMessage("usuario.Invalido")
  @Html.LabelFor(u => u.Nome, "Nome: " )
  @Html.TextBoxFor(u => u.Nome, new {@class = "form-control"})
  @Html.ValidationMessageFor(u => u.Nome)
<br/>
  @Html.LabelFor(u => u.Email, "Email: ")
  @Html.TextBoxFor(u => u.Email, new { @class = "form-control" })
  @Html.ValidationMessageFor(u => u.Email)

<br />
 @Html.LabelFor(u => u.Senha, "Senha:")
 @Html.PasswordFor(u => u.Senha, new { @class = "form-control" })
 @Html.ValidationMessageFor(u => u.Senha)
<br />
@Html.LabelFor(u => u.ConfirmacaoSenha, "Confirme Sua Senha:")
@Html.PasswordFor(u => u.ConfirmacaoSenha, new { @class = "form-control" })
@Html.ValidationMessageFor(u => u.ConfirmacaoSenha)
<br />
 <input type="submit" value="Enviar" class="btn btn-primary" />
}

Financas/Views/Usuario/Index.cshtml
@model IList<Financas.Entidades.Usuario>
    @{
    ViewBag.Title = "Usuarios";
}

@Html.ActionLink("Novo Usuario", "Form")

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>E-mail</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var usuario in Model)
    {
        <tr>
            <td>@usuario.Id</td>
            <td>@usuario.Nome</td>
            <td>@usuario.Email</td>
        </tr>
  
    }
    </tbody>
</table>